### ISSUE TITLE
No public interface to commit a drawing

### ISSUE THREAD

**Issue by chriserickson** [yohanboniface/Leaflet.Editable#12]
I can save my current feature by calling:
`map.editTools._drawingEditor.commitDrawing()`
but it seems that there should be a public interface for this like:
`map.editTools.commitDrawing()`
or 
`map.editTools.stopDrawing(true)`

**Comment by yohanboniface** [comment]
Done in Leaflet1.0 branch (I hope soon merged in master): https://github.com/yohanboniface/Leaflet.Editable/commit/832cfc0030cea5b0777f190d5ffc7c72fc2edd06

Though, I'm curious about your use case where you need to commit but don't have the editor instance around :)
