### ISSUE TITLE
Simple line support

### ISSUE THREAD

**Issue by joaoponceleao** [yohanboniface/Leaflet.Editable#13]
Hi,
I'm trying to use L.Editable (Leaflet 1.0 branch) to create lines (i.e. a geojson polyline with exactly 2 vertices - I'm surprised that geojson does not support lines...). I need this for network analysis, where lines have to be straight and contain only two vertices, but I'm sure others might have other uses for this as well.

I have adapted the tooltips example to achieve this by calling `map.editTools.stopDrawing()` when `e.layer.editor._drawnLatLngs.length` gives me the desired max number of vertices. But I've encountered two problems:

1. If I call `stopDrawing` when the `_drawnLatLngs.length == 1` (i.e. 2 vertices), the line does not get created (the last vertex seems to get removed). If I call it when the length == 2, the line gets created but the user is forced to click twice. Once for the last vertex, and then again to commit. After drawing the last vertex and before committing the line, the usual temporary dashed line is visible, which makes it look like you are continuing the line and is misleading. I would like to reduce the line creation to just 2 clicks, or remove the dashed line after the second click.

2. A more serious problem is what happens after a line is created. The user should have the option to edit the line by moving its vertices. This works well. However, a midpoint vertex is always displayed. If the user drags it, they will add a new vertex, turning it into a polyline. Is there a way to disable this?

Thanks for the library! Any help is appreciated.

Joao

**Comment by joaoponceleao** [comment]
Having looked more closely at the other open thread, I'm assuming the answer for problem 2 is in `editable:middlemarker:mousedown`. So will give that a try. Still not sure how to handle problem 1 though.

**Comment by yohanboniface** [comment]
For 2, you can use `skipMiddleMarkers` L.Editable option.
For 1, it depends which [event](https://github.com/yohanboniface/Leaflet.Editable/tree/leaflet1.0#events) you are using, I would use `editable:drawing:clicked`.

**Comment by joaoponceleao** [comment]
For 1. Yes, I was using the `click` event. That was the problem. Oops.
For 2. Thanks, thats exactly what I was looking for! Don't understand how I missed it in the docs!

Minor issue (hopefully its not my fault again). Whilst `skipMiddleMarkers` works perfectly, hiding and disabling the marker, the cursor still changes when hovering over the midpoint, as if a marker existed.

**Comment by yohanboniface** [comment]
Humm, I can't reproduce, so I'm certainly missing a step.
If I just add `, editOptions: {skipMiddleMarkers: true}` in the `example/index.html`, I don't see any middlemarker again, and even after disabling/enabling edit again. Can you give me a bit more infos on how to reproduce?

**Comment by joaoponceleao** [comment]
As I said, very minor issue (if even that - I was going to close the issue but thought you might want to know). I imagine related to default Leaflet way of handling things.

The middle marker does indeed disappear like you say. Everything works as expected.
The issue is, that the hand cursor changes when hovering over the midpoint (where the middle marker would be if `skipMiddleMarkers` was not used). It has no effect otherwise. Its just that the hand cursor is giving the wrong visual indication. Perhaps this is the default Leaflet behaviour?

I just reproduced this on `index.html` with the leaflet.js commit of 7 Feb, with the code you mentioned:
`L.map('map', {editable: true, editOptions: {skipMiddleMarkers: true}}).setView(startPoint, 16)`

On my app I'm referencing it this way:
```
L.DomEvent.on.......
map.editTools.options.skipMiddleMarkers = true;
....startPolyline();
```
As I need a different behaviour depending on the tool chosen.

**Comment by joaoponceleao** [comment]
Perhaps an image is better. Its that little finger pointing up..... it should not be there (minor, I know....):
![hand](https://cloud.githubusercontent.com/assets/6002614/6129782/b88dfa12-b138-11e4-904d-7f059cd26647.jpg)

**Comment by yohanboniface** [comment]
Humm, but isn't that just because you over the line itself? If you over another point of the line, you don't have the hand?

**Comment by joaoponceleao** [comment]
The finger pops up over a vertices, or middle markers. Otherwise, it just shows a closed hand. In this case, it pops up over a disabled / hidden middle marker as well.

**Comment by joaoponceleao** [comment]
Disregard.... You're right, sorry. It pops up anywhere on the line. Fair enough....
I just noticed the new issue you opened. Is there something wrong with the way I'm calling `skipMiddleMarkers`?

**Comment by yohanboniface** [comment]
But the middle marker itself should not be added at all when using the skip option.
And by default the line if clickable does trigger the finger cursor.
Can I can test/ the code somewhere?

**Comment by yohanboniface** [comment]
> Is there something wrong with the way I'm calling skipMiddleMarkers?

Nope. I just noticed seeing your example that one may want to only skipMiddleMarkers for some editors and not for some others, which is not doable at the moment.

**Comment by joaoponceleao** [comment]
Yes. You're correct. Everything is fine. I was just getting confused with this:
> And by default the line if clickable does trigger the finger cursor.
I thought it would only trigger on markers by default.... my mistake.
Thanks for the reassurance on the code example.
