### ISSUE TITLE
How to enable Editable using Leaflet Angular Directive

### ISSUE THREAD

**Issue by chriseyhorn** [yohanboniface/Leaflet.Editable#20]
I'm using the angular-leaflet-directive and not sure how to enable Editable since the creation of the map object is using an angular directive.  Is there another way to enable after map has been created?

Thanks for any assistance!

**Comment by yohanboniface** [comment]
Not sure how `angular-leaflet-directive` can impact Leaflet actually.
Are you looking for that?

```
map.editTools = new L.Editable(map);
```

**Comment by chriseyhorn** [comment]
Perfect that is what I needed.  I added to my map controller and it is now working.  Thanks!
