### ISSUE TITLE
L.Draw.Polygon events added by Editable Question

### ISSUE THREAD

**Issue by chriseyhorn** [yohanboniface/Leaflet.Editable#21]
If I have an existing Polygon being draw by leaflet.draw, can I use editable to detect when any points of the polygon have been moved?  Do I need to pass anything to the EditTools object to register this polygon with it so that these events will fire?

**Comment by yohanboniface** [comment]
Those events are fired by the vertex markers, so if you are not using vertex markers created by Editable, you'll have no editable events.

I'm curious about the use case where you need both Leaflet.Draw AND Leaflet.Editable.

**Comment by chriseyhorn** [comment]
Hey Yohan,

After digging more into Leaflet.Draw I realized that there is an edit event on the polygon object that will fire when the geometry is changed.  At first glance it appeared that there was only a map edit event that was only firing when the user clicked the save button in the UI toolbar (which I'm not using).

Thanks for your help!

Best Regards,
Chris
