### ISSUE TITLE
Clickhandler switches after having focus out of map

### ISSUE THREAD

**Issue by nwidal** [yohanboniface/Leaflet.Editable#22]
Hi,

I am experiencing the issue that when I am clicking out of the map zone, the click handler seem to switch.
At first a Vertex of a polygon gets deleted by clicking with left mousedown / double tap (on android chromium web view).
When clicking out of the map and trying to delete a vertex again it is right click / shftclick in browser chrome and nothing happens on android chromium.

Tried both the stable and dev 1.0 version (gh-pages)

 map = L.map('map', {editable: true, doubleClickZoom: false, minZoom: 3, maxZoom: 19, zoomControl: false}).setView(startPoint, 16);

                                poly = L.polygon([
                                    [
                                        [lat + polySize, lng],
                                        [lat, lng - polySize],
                                        [lat - polySize, lng],
                                        [lat, lng + polySize]
                                    ]
                                ]);

                                map.addLayer(poly);
                                poly.enableEdit();
                                //Dbl Tap wether to edit or not
                                poly.on('dblclick', L.DomEvent.stop).on('dblclick', poly.toggleEdit);

Using Ionic, Angular - NO jQuery / jQuery Mobile implemented
Any idea appreciated =)

**Comment by yohanboniface** [comment]
Are you able to set up a http://jsfiddle.net/ by chance?

**Comment by nwidal** [comment]
No sorry. At way to airport atm. The issue must sonehow be on ionic side. Can you tell me where the clixkhandlers are registred and how to manipulate them e.g. making rightclick event to leftclick? Is it in leaflet.js? Thanks a mill. :)

**Comment by yohanboniface** [comment]
Hard to understand what's going on without a way to reproduce.
Events are added by Leaflet.Editable [here](https://github.com/yohanboniface/Leaflet.Editable/blob/gh-pages/src/Leaflet.Editable.js#L274), but then managed by Leaflet [here](https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L640) and in other places… :/
Can you see if you reproduce without frameworks?

**Comment by nwidal** [comment]
Thanks - soehow only click event isn't working properly, but has nothing to do with leaflet.editable afaik

**Comment by yohanboniface** [comment]
Closing as it seems no action is required.
