### ISSUE TITLE
fireMouseEvent is not a function

### ISSUE THREAD

**Issue by kaynz** [yohanboniface/Leaflet.Editable#23]
Hey,

when using leaflet.editable with leaflet 1.0:
<pre>
10    843918   error    Uncaught TypeError: this._fireMouseEvent is not a functi
on, http://192.168.178.52:8100/lib/Leaflet.Editable-1.0/src/Leaflet.Editable.js,
 Line: 401
</pre>

This error is thrown when a vertex is touched on mobile touch devices.

**Comment by yohanboniface** [comment]
Which Leaflet.Editable branch are you using and which Leaflet version?

**Comment by kaynz** [comment]
Newest from leaflet master and leaflet.editable gh-pages.

**Comment by yohanboniface** [comment]
Can you try with branch "map-domevent" of Leaflet?

**Comment by yohanboniface** [comment]
Humm, wait a bit, I'm pushing a (possible) fix.

**Comment by kaynz** [comment]
Thanks. With your fix, it was still throwing a  "_handleDOMEvent not a function error".
Doing the following, I could get it running without errors:
<pre>L.DomEvent.on(this._icon, 'touchstart', function (e) {this._map._handleDOMEvent(e);}, this);
</pre>
But my problem remains: I still dont get any events from "click" or "dblclick" from vertex markers (or the whole polygon) on touch devices =(

<pre>
L.Editable.VertexMarker.include ({

    onAdd: function (map) {
        L.Marker.prototype.onAdd.call(this, map);
        this.on('drag', this.onDrag);
        this.on('dragstart', this.onDragStart);
        this.on('dragend', this.onDragEnd);
        this.on('click', this.onClick);
        this.on('dblclick', this.onDblClick);
        this.on('contextmenu', this.onContextMenu);
        this.on('mousedown touchstart', this.onMouseDown);
        this.addMiddleMarkers();
        console.log("added");
    },

    onDblClick: function (e) {
        console.log("test");
        e.vertex = this;
        this.editor.onVertexMarkerClick(e);
    },
});
</pre>

"added" is printed, but there's no "test".

**Comment by yohanboniface** [comment]
> Doing the following, I could get it running without errors:

Gasp! I pushed too quickly.

> I still dont get any events from "click" or "dblclick" from vertex markers (or the whole polygon) on 
> touch devices

DOM events are being reworked in Leaflet master (see  `map-domevent` branch, but it's not finished yet), until then I'm afraid we'll not have a fully operational code here :/

**Comment by yohanboniface** [comment]
Touch should be back to normal support.
