### ISSUE TITLE
Get and delete polylines from Map

### ISSUE THREAD

**Issue by gsingh-cp** [yohanboniface/Leaflet.Editable#26]
Hi

Is there a way for me to get a polyline that was created using map.editTools.startPolyLine() and delete it?

The goal is to have a custom button "New Line" that deletes a line if present and start a new line.

Therefore I would only like 1 drawable line at a time.

I put this.map.editTools; in my init function and have this.map.editTools.startPolyLine() in my button click handler.

Thanks

Using leaflet 0.7.3 + leaflet.editable leaflet0.7 branch.

**Comment by yohanboniface** [comment]
`var line = map.editTools.startPolyLine()` ?

**Comment by gsingh-cp** [comment]
Thanks for the quick reply.

Is there a clear or delete command I can use on this?

**Comment by yohanboniface** [comment]
That's Leaflet API. If you are on 0.7.3, something like `map.removeLayer(line)` should work.

**Comment by gsingh-cp** [comment]
Thank you. That works.

**Comment by yohanboniface** [comment]
:)

**Comment by tuevu2223** [comment]
helo
