### ISSUE TITLE
Enable/Disable a polyline from being edited

### ISSUE THREAD

**Issue by gsingh-cp** [yohanboniface/Leaflet.Editable#27]
Hi

Follow up question.  Is it possible to enable or disable a polyline from being edited after it has been added to a map.

I would basically like to have button that toggles edit mode of a line that was added using the editTools.

Thanks again for your assistance.

**Comment by kaynz** [comment]
polyline.disableEdit()
polyline.enableEdit()

**Comment by gsingh-cp** [comment]
Awesome. Thanks
