### ISSUE TITLE
Single Polyline with JSON

### ISSUE THREAD

**Issue by gsingh-cp** [yohanboniface/Leaflet.Editable#28]
Apologies if this question should be on the leaflet's site.

I have a layerGroup which contains a editable polyline.  

I am able save it's GeoJSON to a variable by doing:
currentLine = this.myLayers.myLine.toGeoJSON()

What is the best way to load data into this editable line?  
this.myLayers.myLine = L.polyline((somehow get the x,y array of what I want to load)?

Or do I need to do something with the GeoJSON layer?

Thanks

**Comment by barnabas-kendall-avalara** [comment]
I am in a similar spot and have been wrestling with this for a bit. How can we round-tip edit GeoJSON? Here's a CodePen to illustrate: http://codepen.io/barnabas-kendall-avalara/pen/jPRZZo/

If we start with leaflet objects like L.polygon, then they are editable. However, if we turn that polygon into GeoJSON, then how can we edit it again? As far as I can tell, L.geoJson does not expose leaflet primitives.

**Comment by gsingh-cp** [comment]
I am doing this at the moment:

this.myLayers.myLine.setLatLngs(savedLine.geometry.coordinates)  

However, the coordinates are flipped.  Therefore the polyline is drawn flipped.

**Comment by barnabas-kendall-avalara** [comment]
I figured this out and edited the CodePen above. The trick is that you can enable editing only after the layer is added to the map. In your case, loading the GeoJSON and editing is simple, something like:

```javascript
var geoData = getGeoJsonData(); // wherever your data comes from
var geoPoly = L.geoJson(geoData);
geoPoly.addTo(map);

geoPoly.eachLayer(function(layer) {
    layer.enableEdit();
});
```

**Comment by yohanboniface** [comment]
@gsingh-cp yes, this is more a Leaflet issue than a Leaflet.Editable specific.

You can use [L.GeoJSON.coordsToLatLng](http://leafletjs.com/reference.html#geojson-coordstolatlng) as a helper before calling `setLatLngs`.

@barnabas-kendall-avalara if you need anymore help, ping me again :)
