### ISSUE TITLE
Create Editable Markers from GeoJSON

### ISSUE THREAD

**Issue by gsingh-cp** [yohanboniface/Leaflet.Editable#30]
Hi All

I have a featureCollection of markers which I want to add to the map and have them editable.

I am doing the following.

      function onEachFeature(feature, layer){
       // TODO: MAKE THEM SNAPABLE AND EDITABLE AND SET CUSTOM ICONS
        self.layers.myMarkers.addLayer(layer);
      }

  L.geoJson(markersFeatures,{
        onEachFeature: onEachFeature
      }).addTo(this.map)

Is this the correct way of doing this?  I can get the basic markers to show up in the layer/map fine. 

Thanks

**Comment by yohanboniface** [comment]
That's a Leaflet question, nothing specific to Leaflet.Editable.
See http://leafletjs.com/examples/geojson.html and call `layer.enableEdit()` on each layer once added to the map.
