### ISSUE TITLE
svg object gets invisible when its root is moved out of the map

### ISSUE THREAD

**Issue by kaynz** [yohanboniface/Leaflet.Editable#32]
Hey,

just found a bug, where a path object gets invisible when you move the map so that its root gets out of the visible area of the map.

I've made a video so things get clear pretty fast.

https://www.youtube.com/watch?v=U7SOvKwLHW8&feature=youtu.be

Thanks.

**Comment by yohanboniface** [comment]
Sounds bad :/

Which versions of Leaflet and Leaflet.Editable are you using?

**Comment by yohanboniface** [comment]
OK, I'm able to reproduce. Will look into this asap. Thanks for the report!

**Comment by yohanboniface** [comment]
Should be fixed. Can you try again to confirm? Thanks :)

**Comment by kaynz** [comment]
Super fast! Will check this on monday! Thanks

**Comment by kaynz** [comment]
Works perfect!

**Comment by yohanboniface** [comment]
Cool, thanks for confirmation :)

**Comment by kaynz** [comment]
@yohanboniface, hey!

Your fix does not work in ur example:
http://yohanboniface.github.io/Leaflet.Editable/example/snapping.html

Any ideas on this?

**Comment by yohanboniface** [comment]
Humm, works for me

**Comment by kaynz** [comment]
https://youtu.be/CSDL61XVyl8

**Comment by yohanboniface** [comment]
Ah ok, the bug is a bit different :/
Let's open a dedicated issue (I'm doing it).
