### ISSUE TITLE
Ctrl+click does not work (Mac)

### ISSUE THREAD

**Issue by salomvary** [yohanboniface/Leaflet.Editable#34]
Tried these demos, nothing happened on ctrl+click (using Mac + Chrome, Firefox):
  
Continue line by ctrl-clicking on first/last point
Create hole in a polygon by ctrl-clicking on it

**Comment by yohanboniface** [comment]
Because Mac override Ctrl-click behaviour. That's just a demo after all, one can implement that with Alt or Shift or whatever ;)
I may add Alt-click too for the demo, though.

**Comment by salomvary** [comment]
What's missing (not from the demo, from the plugin itself) is probably `onVertexMarkerMetaClick`.

**Comment by salomvary** [comment]
...and that enables Cmd+clicking on things, which is usually treated the same way on Mac as Ctrl+click on others.

**Comment by yohanboniface** [comment]
I thought I added metaKey support on the core, but it wasn't, so thanks for the reminder :)

Also updated examples.

**Comment by salomvary** [comment]
Thanks. Nice work on this plugin btw \o/
