### ISSUE TITLE
Middlemarker not updated to draggable vertex marker when clicked

### ISSUE THREAD

**Issue by cmulders** [yohanboniface/Leaflet.Editable#35]
(1) When a middle marker is clicked (so no mouse move), the marker is updated to the vertex marker icon, but the vertex marker is not draggable anymore. 
(2) Any subsequent activated middle markers (regardless of moving) are also broken afterwards

To replicate (1): 
1. Open the Basic Controls example
2. Click (without moving) one (50% opacity) middle marker
3. Try to move the created vertex marker.

To replicate (2):
Steps 1-3 above
4. move a other 'grey' vertex marker (move the marker, so no click)
5. Let go of the marker (marker is now white and additional middle markers are added
5. try to move the marker again

Reproducible in Safari and Chrome

Possibly the event chain is not correct for clicks, because in L.draggable a move event is required to fire the ```dragstart```, ```drag``` and ```dragend``` events.

**Comment by yohanboniface** [comment]
Thanks for the report. Which version of Leaflet and Leaflet.Editable are you using?

**Comment by yohanboniface** [comment]
OK I can reproduce. Actually, even when moving the middle marker.

**Comment by yohanboniface** [comment]
"Guilty" commit is https://github.com/Leaflet/Leaflet/commit/39f03304a6df9fa8f456d2fb05eb3004cc2b7f43

**Comment by cmulders** [comment]
Thanks! Easy fix :+1:
