### ISSUE TITLE
onStopDraggingMarker

### ISSUE THREAD

**Issue by stev-0** [yohanboniface/Leaflet.Editable#37]
Is there an event for this? I have successfully added a marker to the map with the `on('editable:drawing:commit'` but I cannot work out how to signify the end of a marker drag move. Perhaps a new event is required. I will have a look at the source code at some point and see if I can figure out if any changes would be required.

Stephen

**Comment by yohanboniface** [comment]
If you are referring to a vertex marker, you should be able to use `editable:vertex:dragend`. If you are referring to a normal marker you can use the Leaflet `dragend` [event](http://leafletjs.com/reference.html#marker-dragend).
